name = "All the Walfolie 9"
author = "Marcel Petras"
version = "1.0.13"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "657a87eb587e6b3f3ef390960e606476d0c0cb59dd777a23fe2e9fa3198fcd4c"

[versions]
forge = "47.4.20"
minecraft = "1.20.1"
